/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.mobiwiz.cwmwsql.models.query.*;

@Service
public class CWmwSQLQueryExecutorServiceImpl implements CWmwSQLQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CWmwSQLQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("CWmwSQLWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "CWmwSQLTransactionManager", readOnly = true)
    @Override
    public Page<QryDoctorsListResponse> executeQryDoctorsList(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("qryDoctorsList", params, QryDoctorsListResponse.class, pageable);
    }

    @Transactional(value = "CWmwSQLTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQryDoctorsList(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("qryDoctorsList", params, QryDoctorsListResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}