/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.mobiwiz.myauthenticationmanager.controller;

import com.mobiwiz.myauthenticationmanager.MyAuthenticationManager;
import com.wavemaker.runtime.security.AuthRequestContext;
import com.wavemaker.runtime.security.WMUser;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/myAuthenticationManager")
public class MyAuthenticationManagerController {

    @Autowired
    private MyAuthenticationManager myAuthenticationmanager;

    @RequestMapping(value = "/authenticate", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public WMUser authenticate(@RequestBody AuthRequestContext authRequestContext) {
        return myAuthenticationmanager.authenticate(authRequestContext);
    }
}
