/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blueprnt generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`blueprnt`")
public class Blueprnt implements Serializable {

    private Integer blpId = 0;
    private int idNo;
    private String shortname;
    private String longname;
    private byte acolor = 0;
    private byte aicon = 0;
    private short usualdurtn = 0;
    private boolean isconsltn;
    private LocalDateTime revisedon;
    private String revisedby;
    private String checkwith;
    private String blptype;
    private float sortordr = 0F;
    private boolean incalendar;
    private boolean useinprs2;
    private String icdcode1;
    private String icdcode2;
    private String icdcode3;
    private String icdcode4;
    private String icdcode5;
    private String icdcode6;
    private String icdcode7;
    private String icdcode8;
    private short theatrtime = 0;
    private short arrivebefo = 0;
    private String specificto;
    private String autorcl1cd;
    private short autorcl1no = 0;
    private String autorcl1st;
    private String autorcl2cd;
    private short autorcl2no = 0;
    private String autorcl2st;
    private String autorcl3cd;
    private short autorcl3no = 0;
    private String autorcl3st;
    private boolean ask4newref;
    private String specpreper;
    private String docoutcd1;
    private short docoutby1 = 0;
    private String docoutcd2;
    private short docoutby2 = 0;
    private String docoutcd3;
    private short docoutby3 = 0;
    private String docintype1;
    private short docinby1 = 0;
    private String docintype2;
    private short docinby2 = 0;
    private String docintype3;
    private short docinby3 = 0;
    private String formsreq1;
    private short formreqby1 = 0;
    private String formsreq2;
    private short formreqby2 = 0;
    private String formsreq3;
    private short formreqby3 = 0;
    private boolean nochgApt;
    private String apptinfo1;
    private String apptinfo2;
    private String anaethtype;
    private String eclpPtcls;

    @Id
    @Column(name = "`blp_id`", nullable = false, scale = 0, precision = 10)
    public Integer getBlpId() {
        return this.blpId;
    }

    public void setBlpId(Integer blpId) {
        this.blpId = blpId;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }

    @Column(name = "`shortname`", nullable = false, length = 5)
    public String getShortname() {
        return this.shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    @Column(name = "`longname`", nullable = false, length = 40)
    public String getLongname() {
        return this.longname;
    }

    public void setLongname(String longname) {
        this.longname = longname;
    }

    @Column(name = "`acolor`", nullable = false, scale = 0, precision = 2)
    public byte getAcolor() {
        return this.acolor;
    }

    public void setAcolor(byte acolor) {
        this.acolor = acolor;
    }

    @Column(name = "`aicon`", nullable = false, scale = 0, precision = 2)
    public byte getAicon() {
        return this.aicon;
    }

    public void setAicon(byte aicon) {
        this.aicon = aicon;
    }

    @Column(name = "`usualdurtn`", nullable = false, scale = 0, precision = 3)
    public short getUsualdurtn() {
        return this.usualdurtn;
    }

    public void setUsualdurtn(short usualdurtn) {
        this.usualdurtn = usualdurtn;
    }

    @Column(name = "`isconsltn`", nullable = false)
    public boolean isIsconsltn() {
        return this.isconsltn;
    }

    public void setIsconsltn(boolean isconsltn) {
        this.isconsltn = isconsltn;
    }

    @Column(name = "`revisedon`", nullable = false)
    public LocalDateTime getRevisedon() {
        return this.revisedon;
    }

    public void setRevisedon(LocalDateTime revisedon) {
        this.revisedon = revisedon;
    }

    @Column(name = "`revisedby`", nullable = false, length = 5)
    public String getRevisedby() {
        return this.revisedby;
    }

    public void setRevisedby(String revisedby) {
        this.revisedby = revisedby;
    }

    @Column(name = "`checkwith`", nullable = false, length = 10)
    public String getCheckwith() {
        return this.checkwith;
    }

    public void setCheckwith(String checkwith) {
        this.checkwith = checkwith;
    }

    @Column(name = "`blptype`", nullable = false, length = 10)
    public String getBlptype() {
        return this.blptype;
    }

    public void setBlptype(String blptype) {
        this.blptype = blptype;
    }

    @Column(name = "`sortordr`", nullable = false, scale = 1, precision = 5)
    public float getSortordr() {
        return this.sortordr;
    }

    public void setSortordr(float sortordr) {
        this.sortordr = sortordr;
    }

    @Column(name = "`incalendar`", nullable = false)
    public boolean isIncalendar() {
        return this.incalendar;
    }

    public void setIncalendar(boolean incalendar) {
        this.incalendar = incalendar;
    }

    @Column(name = "`useinprs2`", nullable = false)
    public boolean isUseinprs2() {
        return this.useinprs2;
    }

    public void setUseinprs2(boolean useinprs2) {
        this.useinprs2 = useinprs2;
    }

    @Column(name = "`icdcode1`", nullable = false, length = 10)
    public String getIcdcode1() {
        return this.icdcode1;
    }

    public void setIcdcode1(String icdcode1) {
        this.icdcode1 = icdcode1;
    }

    @Column(name = "`icdcode2`", nullable = false, length = 10)
    public String getIcdcode2() {
        return this.icdcode2;
    }

    public void setIcdcode2(String icdcode2) {
        this.icdcode2 = icdcode2;
    }

    @Column(name = "`icdcode3`", nullable = false, length = 10)
    public String getIcdcode3() {
        return this.icdcode3;
    }

    public void setIcdcode3(String icdcode3) {
        this.icdcode3 = icdcode3;
    }

    @Column(name = "`icdcode4`", nullable = false, length = 10)
    public String getIcdcode4() {
        return this.icdcode4;
    }

    public void setIcdcode4(String icdcode4) {
        this.icdcode4 = icdcode4;
    }

    @Column(name = "`icdcode5`", nullable = false, length = 10)
    public String getIcdcode5() {
        return this.icdcode5;
    }

    public void setIcdcode5(String icdcode5) {
        this.icdcode5 = icdcode5;
    }

    @Column(name = "`icdcode6`", nullable = false, length = 10)
    public String getIcdcode6() {
        return this.icdcode6;
    }

    public void setIcdcode6(String icdcode6) {
        this.icdcode6 = icdcode6;
    }

    @Column(name = "`icdcode7`", nullable = false, length = 10)
    public String getIcdcode7() {
        return this.icdcode7;
    }

    public void setIcdcode7(String icdcode7) {
        this.icdcode7 = icdcode7;
    }

    @Column(name = "`icdcode8`", nullable = false, length = 10)
    public String getIcdcode8() {
        return this.icdcode8;
    }

    public void setIcdcode8(String icdcode8) {
        this.icdcode8 = icdcode8;
    }

    @Column(name = "`theatrtime`", nullable = false, scale = 0, precision = 3)
    public short getTheatrtime() {
        return this.theatrtime;
    }

    public void setTheatrtime(short theatrtime) {
        this.theatrtime = theatrtime;
    }

    @Column(name = "`arrivebefo`", nullable = false, scale = 0, precision = 3)
    public short getArrivebefo() {
        return this.arrivebefo;
    }

    public void setArrivebefo(short arrivebefo) {
        this.arrivebefo = arrivebefo;
    }

    @Column(name = "`specificto`", nullable = false, length = 10)
    public String getSpecificto() {
        return this.specificto;
    }

    public void setSpecificto(String specificto) {
        this.specificto = specificto;
    }

    @Column(name = "`autorcl1cd`", nullable = false, length = 10)
    public String getAutorcl1cd() {
        return this.autorcl1cd;
    }

    public void setAutorcl1cd(String autorcl1cd) {
        this.autorcl1cd = autorcl1cd;
    }

    @Column(name = "`autorcl1no`", nullable = false, scale = 0, precision = 4)
    public short getAutorcl1no() {
        return this.autorcl1no;
    }

    public void setAutorcl1no(short autorcl1no) {
        this.autorcl1no = autorcl1no;
    }

    @Column(name = "`autorcl1st`", nullable = false, length = 10)
    public String getAutorcl1st() {
        return this.autorcl1st;
    }

    public void setAutorcl1st(String autorcl1st) {
        this.autorcl1st = autorcl1st;
    }

    @Column(name = "`autorcl2cd`", nullable = false, length = 10)
    public String getAutorcl2cd() {
        return this.autorcl2cd;
    }

    public void setAutorcl2cd(String autorcl2cd) {
        this.autorcl2cd = autorcl2cd;
    }

    @Column(name = "`autorcl2no`", nullable = false, scale = 0, precision = 4)
    public short getAutorcl2no() {
        return this.autorcl2no;
    }

    public void setAutorcl2no(short autorcl2no) {
        this.autorcl2no = autorcl2no;
    }

    @Column(name = "`autorcl2st`", nullable = false, length = 10)
    public String getAutorcl2st() {
        return this.autorcl2st;
    }

    public void setAutorcl2st(String autorcl2st) {
        this.autorcl2st = autorcl2st;
    }

    @Column(name = "`autorcl3cd`", nullable = false, length = 10)
    public String getAutorcl3cd() {
        return this.autorcl3cd;
    }

    public void setAutorcl3cd(String autorcl3cd) {
        this.autorcl3cd = autorcl3cd;
    }

    @Column(name = "`autorcl3no`", nullable = false, scale = 0, precision = 4)
    public short getAutorcl3no() {
        return this.autorcl3no;
    }

    public void setAutorcl3no(short autorcl3no) {
        this.autorcl3no = autorcl3no;
    }

    @Column(name = "`autorcl3st`", nullable = false, length = 10)
    public String getAutorcl3st() {
        return this.autorcl3st;
    }

    public void setAutorcl3st(String autorcl3st) {
        this.autorcl3st = autorcl3st;
    }

    @Column(name = "`ask4newref`", nullable = false)
    public boolean isAsk4newref() {
        return this.ask4newref;
    }

    public void setAsk4newref(boolean ask4newref) {
        this.ask4newref = ask4newref;
    }

    @Column(name = "`specpreper`", nullable = false, length = 2147483647)
    public String getSpecpreper() {
        return this.specpreper;
    }

    public void setSpecpreper(String specpreper) {
        this.specpreper = specpreper;
    }

    @Column(name = "`docoutcd1`", nullable = false, length = 10)
    public String getDocoutcd1() {
        return this.docoutcd1;
    }

    public void setDocoutcd1(String docoutcd1) {
        this.docoutcd1 = docoutcd1;
    }

    @Column(name = "`docoutby1`", nullable = false, scale = 0, precision = 3)
    public short getDocoutby1() {
        return this.docoutby1;
    }

    public void setDocoutby1(short docoutby1) {
        this.docoutby1 = docoutby1;
    }

    @Column(name = "`docoutcd2`", nullable = false, length = 10)
    public String getDocoutcd2() {
        return this.docoutcd2;
    }

    public void setDocoutcd2(String docoutcd2) {
        this.docoutcd2 = docoutcd2;
    }

    @Column(name = "`docoutby2`", nullable = false, scale = 0, precision = 3)
    public short getDocoutby2() {
        return this.docoutby2;
    }

    public void setDocoutby2(short docoutby2) {
        this.docoutby2 = docoutby2;
    }

    @Column(name = "`docoutcd3`", nullable = false, length = 10)
    public String getDocoutcd3() {
        return this.docoutcd3;
    }

    public void setDocoutcd3(String docoutcd3) {
        this.docoutcd3 = docoutcd3;
    }

    @Column(name = "`docoutby3`", nullable = false, scale = 0, precision = 3)
    public short getDocoutby3() {
        return this.docoutby3;
    }

    public void setDocoutby3(short docoutby3) {
        this.docoutby3 = docoutby3;
    }

    @Column(name = "`docintype1`", nullable = false, length = 10)
    public String getDocintype1() {
        return this.docintype1;
    }

    public void setDocintype1(String docintype1) {
        this.docintype1 = docintype1;
    }

    @Column(name = "`docinby1`", nullable = false, scale = 0, precision = 3)
    public short getDocinby1() {
        return this.docinby1;
    }

    public void setDocinby1(short docinby1) {
        this.docinby1 = docinby1;
    }

    @Column(name = "`docintype2`", nullable = false, length = 10)
    public String getDocintype2() {
        return this.docintype2;
    }

    public void setDocintype2(String docintype2) {
        this.docintype2 = docintype2;
    }

    @Column(name = "`docinby2`", nullable = false, scale = 0, precision = 3)
    public short getDocinby2() {
        return this.docinby2;
    }

    public void setDocinby2(short docinby2) {
        this.docinby2 = docinby2;
    }

    @Column(name = "`docintype3`", nullable = false, length = 10)
    public String getDocintype3() {
        return this.docintype3;
    }

    public void setDocintype3(String docintype3) {
        this.docintype3 = docintype3;
    }

    @Column(name = "`docinby3`", nullable = false, scale = 0, precision = 3)
    public short getDocinby3() {
        return this.docinby3;
    }

    public void setDocinby3(short docinby3) {
        this.docinby3 = docinby3;
    }

    @Column(name = "`formsreq1`", nullable = false, length = 10)
    public String getFormsreq1() {
        return this.formsreq1;
    }

    public void setFormsreq1(String formsreq1) {
        this.formsreq1 = formsreq1;
    }

    @Column(name = "`formreqby1`", nullable = false, scale = 0, precision = 3)
    public short getFormreqby1() {
        return this.formreqby1;
    }

    public void setFormreqby1(short formreqby1) {
        this.formreqby1 = formreqby1;
    }

    @Column(name = "`formsreq2`", nullable = false, length = 10)
    public String getFormsreq2() {
        return this.formsreq2;
    }

    public void setFormsreq2(String formsreq2) {
        this.formsreq2 = formsreq2;
    }

    @Column(name = "`formreqby2`", nullable = false, scale = 0, precision = 3)
    public short getFormreqby2() {
        return this.formreqby2;
    }

    public void setFormreqby2(short formreqby2) {
        this.formreqby2 = formreqby2;
    }

    @Column(name = "`formsreq3`", nullable = false, length = 10)
    public String getFormsreq3() {
        return this.formsreq3;
    }

    public void setFormsreq3(String formsreq3) {
        this.formsreq3 = formsreq3;
    }

    @Column(name = "`formreqby3`", nullable = false, scale = 0, precision = 3)
    public short getFormreqby3() {
        return this.formreqby3;
    }

    public void setFormreqby3(short formreqby3) {
        this.formreqby3 = formreqby3;
    }

    @Column(name = "`nochg_apt`", nullable = false)
    public boolean isNochgApt() {
        return this.nochgApt;
    }

    public void setNochgApt(boolean nochgApt) {
        this.nochgApt = nochgApt;
    }

    @Column(name = "`apptinfo1`", nullable = false, length = 2147483647)
    public String getApptinfo1() {
        return this.apptinfo1;
    }

    public void setApptinfo1(String apptinfo1) {
        this.apptinfo1 = apptinfo1;
    }

    @Column(name = "`apptinfo2`", nullable = false, length = 2147483647)
    public String getApptinfo2() {
        return this.apptinfo2;
    }

    public void setApptinfo2(String apptinfo2) {
        this.apptinfo2 = apptinfo2;
    }

    @Column(name = "`anaethtype`", nullable = false, length = 2)
    public String getAnaethtype() {
        return this.anaethtype;
    }

    public void setAnaethtype(String anaethtype) {
        this.anaethtype = anaethtype;
    }

    @Column(name = "`eclp_ptcls`", nullable = false, length = 10)
    public String getEclpPtcls() {
        return this.eclpPtcls;
    }

    public void setEclpPtcls(String eclpPtcls) {
        this.eclpPtcls = eclpPtcls;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Blueprnt)) return false;
        final Blueprnt blueprnt = (Blueprnt) o;
        return Objects.equals(getBlpId(), blueprnt.getBlpId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBlpId());
    }
}