/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hlthfund generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`hlthfund`")
public class Hlthfund implements Serializable {

    private String fundcode;
    private int idNo;
    private String accountno;
    private String company;
    private String address1;
    private String address2;
    private String surburb;
    private String postcode;
    private String state;
    private String title;
    private String surname;
    private String given;
    private String position;
    private String phoneBh;
    private String phoneAh;
    private String fax;
    private String fundgroup;
    private String prs2code;
    private boolean allin1bill;
    private String payerid;
    private String email;
    private boolean indivinvcs;
    private String prfcomunic;
    private boolean ok2email;
    private String fundbrndid;
    private String ifccode;
    private String findisind;
    private String gaptype;
    private float maxdrfee = 0F;
    private byte pref4gap = 0;

    @Id
    @Column(name = "`fundcode`", nullable = false, length = 10)
    public String getFundcode() {
        return this.fundcode;
    }

    public void setFundcode(String fundcode) {
        this.fundcode = fundcode;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }

    @Column(name = "`accountno`", nullable = false, length = 10)
    public String getAccountno() {
        return this.accountno;
    }

    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    @Column(name = "`company`", nullable = false, length = 50)
    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Column(name = "`address1`", nullable = false, length = 30)
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "`address2`", nullable = false, length = 20)
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "`surburb`", nullable = false, length = 20)
    public String getSurburb() {
        return this.surburb;
    }

    public void setSurburb(String surburb) {
        this.surburb = surburb;
    }

    @Column(name = "`postcode`", nullable = false, length = 4)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Column(name = "`state`", nullable = false, length = 3)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`title`", nullable = false, length = 7)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "`surname`", nullable = false, length = 35)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "`given`", nullable = false, length = 25)
    public String getGiven() {
        return this.given;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    @Column(name = "`position`", nullable = false, length = 20)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @Column(name = "`phone_bh`", nullable = false, length = 14)
    public String getPhoneBh() {
        return this.phoneBh;
    }

    public void setPhoneBh(String phoneBh) {
        this.phoneBh = phoneBh;
    }

    @Column(name = "`phone_ah`", nullable = false, length = 14)
    public String getPhoneAh() {
        return this.phoneAh;
    }

    public void setPhoneAh(String phoneAh) {
        this.phoneAh = phoneAh;
    }

    @Column(name = "`fax`", nullable = false, length = 14)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "`fundgroup`", nullable = false, length = 10)
    public String getFundgroup() {
        return this.fundgroup;
    }

    public void setFundgroup(String fundgroup) {
        this.fundgroup = fundgroup;
    }

    @Column(name = "`prs2code`", nullable = false, length = 3)
    public String getPrs2code() {
        return this.prs2code;
    }

    public void setPrs2code(String prs2code) {
        this.prs2code = prs2code;
    }

    @Column(name = "`allin1bill`", nullable = false)
    public boolean isAllin1bill() {
        return this.allin1bill;
    }

    public void setAllin1bill(boolean allin1bill) {
        this.allin1bill = allin1bill;
    }

    @Column(name = "`payerid`", nullable = false, length = 2)
    public String getPayerid() {
        return this.payerid;
    }

    public void setPayerid(String payerid) {
        this.payerid = payerid;
    }

    @Column(name = "`email`", nullable = false, length = 49)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "`indivinvcs`", nullable = false)
    public boolean isIndivinvcs() {
        return this.indivinvcs;
    }

    public void setIndivinvcs(boolean indivinvcs) {
        this.indivinvcs = indivinvcs;
    }

    @Column(name = "`prfcomunic`", nullable = false, length = 10)
    public String getPrfcomunic() {
        return this.prfcomunic;
    }

    public void setPrfcomunic(String prfcomunic) {
        this.prfcomunic = prfcomunic;
    }

    @Column(name = "`ok2email`", nullable = false)
    public boolean isOk2email() {
        return this.ok2email;
    }

    public void setOk2email(boolean ok2email) {
        this.ok2email = ok2email;
    }

    @Column(name = "`fundbrndid`", nullable = false, length = 10)
    public String getFundbrndid() {
        return this.fundbrndid;
    }

    public void setFundbrndid(String fundbrndid) {
        this.fundbrndid = fundbrndid;
    }

    @Column(name = "`ifccode`", nullable = false, length = 1)
    public String getIfccode() {
        return this.ifccode;
    }

    public void setIfccode(String ifccode) {
        this.ifccode = ifccode;
    }

    @Column(name = "`findisind`", nullable = false, length = 1)
    public String getFindisind() {
        return this.findisind;
    }

    public void setFindisind(String findisind) {
        this.findisind = findisind;
    }

    @Column(name = "`gaptype`", nullable = false, length = 1)
    public String getGaptype() {
        return this.gaptype;
    }

    public void setGaptype(String gaptype) {
        this.gaptype = gaptype;
    }

    @Column(name = "`maxdrfee`", nullable = false, scale = 2, precision = 7)
    public float getMaxdrfee() {
        return this.maxdrfee;
    }

    public void setMaxdrfee(float maxdrfee) {
        this.maxdrfee = maxdrfee;
    }

    @Column(name = "`pref4gap`", nullable = false, scale = 0, precision = 1)
    public byte getPref4gap() {
        return this.pref4gap;
    }

    public void setPref4gap(byte pref4gap) {
        this.pref4gap = pref4gap;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Hlthfund)) return false;
        final Hlthfund hlthfund = (Hlthfund) o;
        return Objects.equals(getFundcode(), hlthfund.getFundcode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFundcode());
    }
}