/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class PostcodeId implements Serializable {

    private String areaname;
    private String postcode;
    private String state;

    public String getAreaname() {
        return this.areaname;
    }

    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Postcode)) return false;
        final Postcode postcodeInstance = (Postcode) o;
        return Objects.equals(getAreaname(), postcodeInstance.getAreaname()) &&
                Objects.equals(getPostcode(), postcodeInstance.getPostcode()) &&
                Objects.equals(getState(), postcodeInstance.getState());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAreaname(),
                getPostcode(),
                getState());
    }
}