/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ptdetail generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ptdetail`")
public class Ptdetail implements Serializable {

    private String patientNo;
    private String accountno;
    private String title;
    private String given;
    private String surname;
    private String address1;
    private String address2;
    private String suburb;
    private String postcode;
    private String state;
    private String phoneAh;
    private String phoneBh;
    private String mobile;
    private String sex;
    private LocalDateTime dob;
    private float age = 0F;
    private String birthplace;
    private boolean aboriginal;
    private String maritalst;
    private String religion;
    private String relatnship;
    private String medicareno;
    private String mcaresufix;
    private String employer;
    private String occupation;
    private String hlthbencrd;
    private String vetaffno;
    private String socialno;
    private String pensionno;
    private String hlthcrdno;
    private String medrecflno;
    private String memberNo;
    private String contributr;
    private String coverdesc;
    private String tableSchd;
    private LocalDateTime datejoined;
    private String insurlevel;
    private LocalDateTime lastvist;
    private String allergies;
    private String refdocId;
    private LocalDateTime refdate;
    private byte norefrlexp = 0;
    private LocalDateTime recaladate;
    private String recalreasn;
    private String doctorId;
    private String fundcode;
    private byte labelprnt = 0;
    private byte reportprnt = 0;
    private byte invPrnt = 0;
    private byte rcptPrnt = 0;
    private LocalDateTime changedon;
    private String hosptlurno;
    private byte feepositn = 0;
    private String meddirkey;
    private String comments;
    private String famlyhist;
    private String doctsnotes;
    private String critnotes;
    private String email;
    private String ptstatus;
    private LocalDateTime mediexpry;
    private String othrrefdoc;
    private String prfcomunic;
    private boolean ok2email;
    private boolean pyesno01;
    private boolean pyesno02;
    private boolean pyesno03;
    private boolean pyesno04;
    private boolean pyesno05;
    private double pnumval01 = 0D;
    private double pnumval02 = 0D;
    private String pcharval01;
    private String pcharval02;
    private String pcharval03;
    private LocalDateTime pdateval01;
    private LocalDateTime pdateval02;
    private LocalDateTime pdateval03;
    private boolean hascopmt;
    private float excessamt = 0F;
    private String nextofkin;
    private String checkout;
    private int checksum = 0;
    private String medcrefno;
    private LocalDateTime lastegbchk;
    private String fundupi;
    private String aliasgname;
    private String aliassname;
    private String lastfundst;
    private String lastmedcst;
    private String mcareIrn;
    private String mcareRefn;
    private LocalDateTime lastfnstdt;
    private LocalDateTime lastmcstdt;
    private String minitial;
    private LocalDateTime refissuedt;
    private String referalsrc;
    private String copyto;
    private String copyothers;
    private String claimdtls;
    private LocalDateTime othrrefdte;
    private byte othrrefexp = 0;
    private LocalDateTime pensexpiry;
    private LocalDateTime dvaexpiry;
    private byte dvacardtyp = 0;
    private String indgenstyp;
    private LocalDateTime datecreate;
    private LocalDateTime hlthcrdexp;
    private int idNo;

    @Id
    @Column(name = "`patient_no`", nullable = false, length = 14)
    public String getPatientNo() {
        return this.patientNo;
    }

    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo;
    }

    @Column(name = "`accountno`", nullable = false, length = 10)
    public String getAccountno() {
        return this.accountno;
    }

    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    @Column(name = "`title`", nullable = false, length = 10)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "`given`", nullable = false, length = 50)
    public String getGiven() {
        return this.given;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    @Column(name = "`surname`", nullable = false, length = 25)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "`address1`", nullable = false, length = 50)
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "`address2`", nullable = false, length = 30)
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "`suburb`", nullable = false, length = 20)
    public String getSuburb() {
        return this.suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    @Column(name = "`postcode`", nullable = false, length = 4)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Column(name = "`state`", nullable = false, length = 3)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`phone_ah`", nullable = false, length = 14)
    public String getPhoneAh() {
        return this.phoneAh;
    }

    public void setPhoneAh(String phoneAh) {
        this.phoneAh = phoneAh;
    }

    @Column(name = "`phone_bh`", nullable = false, length = 14)
    public String getPhoneBh() {
        return this.phoneBh;
    }

    public void setPhoneBh(String phoneBh) {
        this.phoneBh = phoneBh;
    }

    @Column(name = "`mobile`", nullable = false, length = 14)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "`sex`", nullable = false, length = 1)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "`dob`", nullable = false)
    public LocalDateTime getDob() {
        return this.dob;
    }

    public void setDob(LocalDateTime dob) {
        this.dob = dob;
    }

    @Column(name = "`age`", nullable = false, scale = 2, precision = 6)
    public float getAge() {
        return this.age;
    }

    public void setAge(float age) {
        this.age = age;
    }

    @Column(name = "`birthplace`", nullable = false, length = 4)
    public String getBirthplace() {
        return this.birthplace;
    }

    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    @Column(name = "`aboriginal`", nullable = false)
    public boolean isAboriginal() {
        return this.aboriginal;
    }

    public void setAboriginal(boolean aboriginal) {
        this.aboriginal = aboriginal;
    }

    @Column(name = "`maritalst`", nullable = false, length = 1)
    public String getMaritalst() {
        return this.maritalst;
    }

    public void setMaritalst(String maritalst) {
        this.maritalst = maritalst;
    }

    @Column(name = "`religion`", nullable = false, length = 10)
    public String getReligion() {
        return this.religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    @Column(name = "`relatnship`", nullable = false, length = 20)
    public String getRelatnship() {
        return this.relatnship;
    }

    public void setRelatnship(String relatnship) {
        this.relatnship = relatnship;
    }

    @Column(name = "`medicareno`", nullable = false, length = 14)
    public String getMedicareno() {
        return this.medicareno;
    }

    public void setMedicareno(String medicareno) {
        this.medicareno = medicareno;
    }

    @Column(name = "`mcaresufix`", nullable = false, length = 3)
    public String getMcaresufix() {
        return this.mcaresufix;
    }

    public void setMcaresufix(String mcaresufix) {
        this.mcaresufix = mcaresufix;
    }

    @Column(name = "`employer`", nullable = false, length = 20)
    public String getEmployer() {
        return this.employer;
    }

    public void setEmployer(String employer) {
        this.employer = employer;
    }

    @Column(name = "`occupation`", nullable = false, length = 25)
    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    @Column(name = "`hlthbencrd`", nullable = false, length = 12)
    public String getHlthbencrd() {
        return this.hlthbencrd;
    }

    public void setHlthbencrd(String hlthbencrd) {
        this.hlthbencrd = hlthbencrd;
    }

    @Column(name = "`vetaffno`", nullable = false, length = 12)
    public String getVetaffno() {
        return this.vetaffno;
    }

    public void setVetaffno(String vetaffno) {
        this.vetaffno = vetaffno;
    }

    @Column(name = "`socialno`", nullable = false, length = 12)
    public String getSocialno() {
        return this.socialno;
    }

    public void setSocialno(String socialno) {
        this.socialno = socialno;
    }

    @Column(name = "`pensionno`", nullable = false, length = 12)
    public String getPensionno() {
        return this.pensionno;
    }

    public void setPensionno(String pensionno) {
        this.pensionno = pensionno;
    }

    @Column(name = "`hlthcrdno`", nullable = false, length = 12)
    public String getHlthcrdno() {
        return this.hlthcrdno;
    }

    public void setHlthcrdno(String hlthcrdno) {
        this.hlthcrdno = hlthcrdno;
    }

    @Column(name = "`medrecflno`", nullable = false, length = 15)
    public String getMedrecflno() {
        return this.medrecflno;
    }

    public void setMedrecflno(String medrecflno) {
        this.medrecflno = medrecflno;
    }

    @Column(name = "`member_no`", nullable = false, length = 14)
    public String getMemberNo() {
        return this.memberNo;
    }

    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo;
    }

    @Column(name = "`contributr`", nullable = false, length = 25)
    public String getContributr() {
        return this.contributr;
    }

    public void setContributr(String contributr) {
        this.contributr = contributr;
    }

    @Column(name = "`coverdesc`", nullable = false, length = 20)
    public String getCoverdesc() {
        return this.coverdesc;
    }

    public void setCoverdesc(String coverdesc) {
        this.coverdesc = coverdesc;
    }

    @Column(name = "`table_schd`", nullable = false, length = 10)
    public String getTableSchd() {
        return this.tableSchd;
    }

    public void setTableSchd(String tableSchd) {
        this.tableSchd = tableSchd;
    }

    @Column(name = "`datejoined`", nullable = false)
    public LocalDateTime getDatejoined() {
        return this.datejoined;
    }

    public void setDatejoined(LocalDateTime datejoined) {
        this.datejoined = datejoined;
    }

    @Column(name = "`insurlevel`", nullable = false, length = 1)
    public String getInsurlevel() {
        return this.insurlevel;
    }

    public void setInsurlevel(String insurlevel) {
        this.insurlevel = insurlevel;
    }

    @Column(name = "`lastvist`", nullable = false)
    public LocalDateTime getLastvist() {
        return this.lastvist;
    }

    public void setLastvist(LocalDateTime lastvist) {
        this.lastvist = lastvist;
    }

    @Column(name = "`allergies`", nullable = false, length = 2147483647)
    public String getAllergies() {
        return this.allergies;
    }

    public void setAllergies(String allergies) {
        this.allergies = allergies;
    }

    @Column(name = "`refdoc_id`", nullable = false, length = 10)
    public String getRefdocId() {
        return this.refdocId;
    }

    public void setRefdocId(String refdocId) {
        this.refdocId = refdocId;
    }

    @Column(name = "`refdate`", nullable = false)
    public LocalDateTime getRefdate() {
        return this.refdate;
    }

    public void setRefdate(LocalDateTime refdate) {
        this.refdate = refdate;
    }

    @Column(name = "`norefrlexp`", nullable = false, scale = 0, precision = 2)
    public byte getNorefrlexp() {
        return this.norefrlexp;
    }

    public void setNorefrlexp(byte norefrlexp) {
        this.norefrlexp = norefrlexp;
    }

    @Column(name = "`recaladate`", nullable = false)
    public LocalDateTime getRecaladate() {
        return this.recaladate;
    }

    public void setRecaladate(LocalDateTime recaladate) {
        this.recaladate = recaladate;
    }

    @Column(name = "`recalreasn`", nullable = false, length = 40)
    public String getRecalreasn() {
        return this.recalreasn;
    }

    public void setRecalreasn(String recalreasn) {
        this.recalreasn = recalreasn;
    }

    @Column(name = "`doctor_id`", nullable = false, length = 10)
    public String getDoctorId() {
        return this.doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    @Column(name = "`fundcode`", nullable = false, length = 10)
    public String getFundcode() {
        return this.fundcode;
    }

    public void setFundcode(String fundcode) {
        this.fundcode = fundcode;
    }

    @Column(name = "`labelprnt`", nullable = false, scale = 0, precision = 2)
    public byte getLabelprnt() {
        return this.labelprnt;
    }

    public void setLabelprnt(byte labelprnt) {
        this.labelprnt = labelprnt;
    }

    @Column(name = "`reportprnt`", nullable = false, scale = 0, precision = 2)
    public byte getReportprnt() {
        return this.reportprnt;
    }

    public void setReportprnt(byte reportprnt) {
        this.reportprnt = reportprnt;
    }

    @Column(name = "`inv_prnt`", nullable = false, scale = 0, precision = 2)
    public byte getInvPrnt() {
        return this.invPrnt;
    }

    public void setInvPrnt(byte invPrnt) {
        this.invPrnt = invPrnt;
    }

    @Column(name = "`rcpt_prnt`", nullable = false, scale = 0, precision = 2)
    public byte getRcptPrnt() {
        return this.rcptPrnt;
    }

    public void setRcptPrnt(byte rcptPrnt) {
        this.rcptPrnt = rcptPrnt;
    }

    @Column(name = "`changedon`", nullable = false)
    public LocalDateTime getChangedon() {
        return this.changedon;
    }

    public void setChangedon(LocalDateTime changedon) {
        this.changedon = changedon;
    }

    @Column(name = "`hosptlurno`", nullable = false, length = 14)
    public String getHosptlurno() {
        return this.hosptlurno;
    }

    public void setHosptlurno(String hosptlurno) {
        this.hosptlurno = hosptlurno;
    }

    @Column(name = "`feepositn`", nullable = false, scale = 0, precision = 2)
    public byte getFeepositn() {
        return this.feepositn;
    }

    public void setFeepositn(byte feepositn) {
        this.feepositn = feepositn;
    }

    @Column(name = "`meddirkey`", nullable = false, length = 9)
    public String getMeddirkey() {
        return this.meddirkey;
    }

    public void setMeddirkey(String meddirkey) {
        this.meddirkey = meddirkey;
    }

    @Column(name = "`comments`", nullable = false, length = 2147483647)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "`famlyhist`", nullable = false, length = 2147483647)
    public String getFamlyhist() {
        return this.famlyhist;
    }

    public void setFamlyhist(String famlyhist) {
        this.famlyhist = famlyhist;
    }

    @Column(name = "`doctsnotes`", nullable = false, length = 2147483647)
    public String getDoctsnotes() {
        return this.doctsnotes;
    }

    public void setDoctsnotes(String doctsnotes) {
        this.doctsnotes = doctsnotes;
    }

    @Column(name = "`critnotes`", nullable = false, length = 2147483647)
    public String getCritnotes() {
        return this.critnotes;
    }

    public void setCritnotes(String critnotes) {
        this.critnotes = critnotes;
    }

    @Column(name = "`email`", nullable = false, length = 49)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "`ptstatus`", nullable = false, length = 20)
    public String getPtstatus() {
        return this.ptstatus;
    }

    public void setPtstatus(String ptstatus) {
        this.ptstatus = ptstatus;
    }

    @Column(name = "`mediexpry`", nullable = false)
    public LocalDateTime getMediexpry() {
        return this.mediexpry;
    }

    public void setMediexpry(LocalDateTime mediexpry) {
        this.mediexpry = mediexpry;
    }

    @Column(name = "`othrrefdoc`", nullable = false, length = 10)
    public String getOthrrefdoc() {
        return this.othrrefdoc;
    }

    public void setOthrrefdoc(String othrrefdoc) {
        this.othrrefdoc = othrrefdoc;
    }

    @Column(name = "`prfcomunic`", nullable = false, length = 10)
    public String getPrfcomunic() {
        return this.prfcomunic;
    }

    public void setPrfcomunic(String prfcomunic) {
        this.prfcomunic = prfcomunic;
    }

    @Column(name = "`ok2email`", nullable = false)
    public boolean isOk2email() {
        return this.ok2email;
    }

    public void setOk2email(boolean ok2email) {
        this.ok2email = ok2email;
    }

    @Column(name = "`pyesno01`", nullable = false)
    public boolean isPyesno01() {
        return this.pyesno01;
    }

    public void setPyesno01(boolean pyesno01) {
        this.pyesno01 = pyesno01;
    }

    @Column(name = "`pyesno02`", nullable = false)
    public boolean isPyesno02() {
        return this.pyesno02;
    }

    public void setPyesno02(boolean pyesno02) {
        this.pyesno02 = pyesno02;
    }

    @Column(name = "`pyesno03`", nullable = false)
    public boolean isPyesno03() {
        return this.pyesno03;
    }

    public void setPyesno03(boolean pyesno03) {
        this.pyesno03 = pyesno03;
    }

    @Column(name = "`pyesno04`", nullable = false)
    public boolean isPyesno04() {
        return this.pyesno04;
    }

    public void setPyesno04(boolean pyesno04) {
        this.pyesno04 = pyesno04;
    }

    @Column(name = "`pyesno05`", nullable = false)
    public boolean isPyesno05() {
        return this.pyesno05;
    }

    public void setPyesno05(boolean pyesno05) {
        this.pyesno05 = pyesno05;
    }

    @Column(name = "`pnumval01`", nullable = false, scale = 2, precision = 8)
    public double getPnumval01() {
        return this.pnumval01;
    }

    public void setPnumval01(double pnumval01) {
        this.pnumval01 = pnumval01;
    }

    @Column(name = "`pnumval02`", nullable = false, scale = 2, precision = 8)
    public double getPnumval02() {
        return this.pnumval02;
    }

    public void setPnumval02(double pnumval02) {
        this.pnumval02 = pnumval02;
    }

    @Column(name = "`pcharval01`", nullable = false, length = 20)
    public String getPcharval01() {
        return this.pcharval01;
    }

    public void setPcharval01(String pcharval01) {
        this.pcharval01 = pcharval01;
    }

    @Column(name = "`pcharval02`", nullable = false, length = 10)
    public String getPcharval02() {
        return this.pcharval02;
    }

    public void setPcharval02(String pcharval02) {
        this.pcharval02 = pcharval02;
    }

    @Column(name = "`pcharval03`", nullable = false, length = 10)
    public String getPcharval03() {
        return this.pcharval03;
    }

    public void setPcharval03(String pcharval03) {
        this.pcharval03 = pcharval03;
    }

    @Column(name = "`pdateval01`", nullable = false)
    public LocalDateTime getPdateval01() {
        return this.pdateval01;
    }

    public void setPdateval01(LocalDateTime pdateval01) {
        this.pdateval01 = pdateval01;
    }

    @Column(name = "`pdateval02`", nullable = false)
    public LocalDateTime getPdateval02() {
        return this.pdateval02;
    }

    public void setPdateval02(LocalDateTime pdateval02) {
        this.pdateval02 = pdateval02;
    }

    @Column(name = "`pdateval03`", nullable = false)
    public LocalDateTime getPdateval03() {
        return this.pdateval03;
    }

    public void setPdateval03(LocalDateTime pdateval03) {
        this.pdateval03 = pdateval03;
    }

    @Column(name = "`hascopmt`", nullable = false)
    public boolean isHascopmt() {
        return this.hascopmt;
    }

    public void setHascopmt(boolean hascopmt) {
        this.hascopmt = hascopmt;
    }

    @Column(name = "`excessamt`", nullable = false, scale = 2, precision = 7)
    public float getExcessamt() {
        return this.excessamt;
    }

    public void setExcessamt(float excessamt) {
        this.excessamt = excessamt;
    }

    @Column(name = "`nextofkin`", nullable = false, length = 2147483647)
    public String getNextofkin() {
        return this.nextofkin;
    }

    public void setNextofkin(String nextofkin) {
        this.nextofkin = nextofkin;
    }

    @Column(name = "`checkout`", nullable = false, length = 25)
    public String getCheckout() {
        return this.checkout;
    }

    public void setCheckout(String checkout) {
        this.checkout = checkout;
    }

    @Column(name = "`checksum`", nullable = false, scale = 0, precision = 10)
    public int getChecksum() {
        return this.checksum;
    }

    public void setChecksum(int checksum) {
        this.checksum = checksum;
    }

    @Column(name = "`medcrefno`", nullable = false, length = 2)
    public String getMedcrefno() {
        return this.medcrefno;
    }

    public void setMedcrefno(String medcrefno) {
        this.medcrefno = medcrefno;
    }

    @Column(name = "`lastegbchk`", nullable = false)
    public LocalDateTime getLastegbchk() {
        return this.lastegbchk;
    }

    public void setLastegbchk(LocalDateTime lastegbchk) {
        this.lastegbchk = lastegbchk;
    }

    @Column(name = "`fundupi`", nullable = false, length = 2)
    public String getFundupi() {
        return this.fundupi;
    }

    public void setFundupi(String fundupi) {
        this.fundupi = fundupi;
    }

    @Column(name = "`aliasgname`", nullable = false, length = 35)
    public String getAliasgname() {
        return this.aliasgname;
    }

    public void setAliasgname(String aliasgname) {
        this.aliasgname = aliasgname;
    }

    @Column(name = "`aliassname`", nullable = false, length = 45)
    public String getAliassname() {
        return this.aliassname;
    }

    public void setAliassname(String aliassname) {
        this.aliassname = aliassname;
    }

    @Column(name = "`lastfundst`", nullable = false, length = 20)
    public String getLastfundst() {
        return this.lastfundst;
    }

    public void setLastfundst(String lastfundst) {
        this.lastfundst = lastfundst;
    }

    @Column(name = "`lastmedcst`", nullable = false, length = 10)
    public String getLastmedcst() {
        return this.lastmedcst;
    }

    public void setLastmedcst(String lastmedcst) {
        this.lastmedcst = lastmedcst;
    }

    @Column(name = "`mcare_irn`", nullable = false, length = 2)
    public String getMcareIrn() {
        return this.mcareIrn;
    }

    public void setMcareIrn(String mcareIrn) {
        this.mcareIrn = mcareIrn;
    }

    @Column(name = "`mcare_refn`", nullable = false, length = 2)
    public String getMcareRefn() {
        return this.mcareRefn;
    }

    public void setMcareRefn(String mcareRefn) {
        this.mcareRefn = mcareRefn;
    }

    @Column(name = "`lastfnstdt`", nullable = false)
    public LocalDateTime getLastfnstdt() {
        return this.lastfnstdt;
    }

    public void setLastfnstdt(LocalDateTime lastfnstdt) {
        this.lastfnstdt = lastfnstdt;
    }

    @Column(name = "`lastmcstdt`", nullable = false)
    public LocalDateTime getLastmcstdt() {
        return this.lastmcstdt;
    }

    public void setLastmcstdt(LocalDateTime lastmcstdt) {
        this.lastmcstdt = lastmcstdt;
    }

    @Column(name = "`m_initial`", nullable = false, length = 5)
    public String getMinitial() {
        return this.minitial;
    }

    public void setMinitial(String minitial) {
        this.minitial = minitial;
    }

    @Column(name = "`refissuedt`", nullable = false)
    public LocalDateTime getRefissuedt() {
        return this.refissuedt;
    }

    public void setRefissuedt(LocalDateTime refissuedt) {
        this.refissuedt = refissuedt;
    }

    @Column(name = "`referalsrc`", nullable = false, length = 2)
    public String getReferalsrc() {
        return this.referalsrc;
    }

    public void setReferalsrc(String referalsrc) {
        this.referalsrc = referalsrc;
    }

    @Column(name = "`copyto`", nullable = false, length = 2147483647)
    public String getCopyto() {
        return this.copyto;
    }

    public void setCopyto(String copyto) {
        this.copyto = copyto;
    }

    @Column(name = "`copyothers`", nullable = false, length = 2147483647)
    public String getCopyothers() {
        return this.copyothers;
    }

    public void setCopyothers(String copyothers) {
        this.copyothers = copyothers;
    }

    @Column(name = "`claimdtls`", nullable = false, length = 2147483647)
    public String getClaimdtls() {
        return this.claimdtls;
    }

    public void setClaimdtls(String claimdtls) {
        this.claimdtls = claimdtls;
    }

    @Column(name = "`othrrefdte`", nullable = false)
    public LocalDateTime getOthrrefdte() {
        return this.othrrefdte;
    }

    public void setOthrrefdte(LocalDateTime othrrefdte) {
        this.othrrefdte = othrrefdte;
    }

    @Column(name = "`othrrefexp`", nullable = false, scale = 0, precision = 2)
    public byte getOthrrefexp() {
        return this.othrrefexp;
    }

    public void setOthrrefexp(byte othrrefexp) {
        this.othrrefexp = othrrefexp;
    }

    @Column(name = "`pensexpiry`", nullable = false)
    public LocalDateTime getPensexpiry() {
        return this.pensexpiry;
    }

    public void setPensexpiry(LocalDateTime pensexpiry) {
        this.pensexpiry = pensexpiry;
    }

    @Column(name = "`dvaexpiry`", nullable = false)
    public LocalDateTime getDvaexpiry() {
        return this.dvaexpiry;
    }

    public void setDvaexpiry(LocalDateTime dvaexpiry) {
        this.dvaexpiry = dvaexpiry;
    }

    @Column(name = "`dvacardtyp`", nullable = false, scale = 0, precision = 1)
    public byte getDvacardtyp() {
        return this.dvacardtyp;
    }

    public void setDvacardtyp(byte dvacardtyp) {
        this.dvacardtyp = dvacardtyp;
    }

    @Column(name = "`indgenstyp`", nullable = false, length = 1)
    public String getIndgenstyp() {
        return this.indgenstyp;
    }

    public void setIndgenstyp(String indgenstyp) {
        this.indgenstyp = indgenstyp;
    }

    @Column(name = "`datecreate`", nullable = false)
    public LocalDateTime getDatecreate() {
        return this.datecreate;
    }

    public void setDatecreate(LocalDateTime datecreate) {
        this.datecreate = datecreate;
    }

    @Column(name = "`hlthcrdexp`", nullable = false)
    public LocalDateTime getHlthcrdexp() {
        return this.hlthcrdexp;
    }

    public void setHlthcrdexp(LocalDateTime hlthcrdexp) {
        this.hlthcrdexp = hlthcrdexp;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Ptdetail)) return false;
        final Ptdetail ptdetail = (Ptdetail) o;
        return Objects.equals(getPatientNo(), ptdetail.getPatientNo());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPatientNo());
    }
}