/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Refrlsrc generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`refrlsrc`")
public class Refrlsrc implements Serializable {

    private String refsrcId;
    private String refsrcdesc;
    private float sortordr = 0F;
    private int idno;

    @Id
    @Column(name = "`refsrc_id`", nullable = false, length = 2)
    public String getRefsrcId() {
        return this.refsrcId;
    }

    public void setRefsrcId(String refsrcId) {
        this.refsrcId = refsrcId;
    }

    @Column(name = "`refsrcdesc`", nullable = false, length = 30)
    public String getRefsrcdesc() {
        return this.refsrcdesc;
    }

    public void setRefsrcdesc(String refsrcdesc) {
        this.refsrcdesc = refsrcdesc;
    }

    @Column(name = "`sortordr`", nullable = false, scale = 1, precision = 5)
    public float getSortordr() {
        return this.sortordr;
    }

    public void setSortordr(float sortordr) {
        this.sortordr = sortordr;
    }

    @Column(name = "`Idno`", nullable = false, scale = 0, precision = 10)
    public int getIdno() {
        return this.idno;
    }

    public void setIdno(int idno) {
        this.idno = idno;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Refrlsrc)) return false;
        final Refrlsrc refrlsrc = (Refrlsrc) o;
        return Objects.equals(getRefsrcId(), refrlsrc.getRefsrcId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRefsrcId());
    }
}