/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Resource generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`resource`")
public class Resource implements Serializable {

    private String resorceId;
    private int idNo;
    private String accountno;
    private String address1;
    private String address2;
    private boolean canDblbuk;
    private float chargerate = 0F;
    private String chargetype;
    private String comments;
    private boolean defaultval;
    private String doctorId;
    private String fax;
    private float flatCharg = 0F;
    private String given;
    private float initCharg = 0F;
    private String mobile;
    private String paging;
    private String phoneAh;
    private String phoneBh;
    private String postcode;
    private String company;
    private String providerno;
    private String qualifictn;
    private String rateUnit;
    private String resrcetype;
    private String schedlrId;
    private String state;
    private String suburb;
    private String surname;
    private String title;
    private String type;
    private String typedetl;
    private short usualdurtn = 0;
    private float usualendt = 0F;
    private float usualstrtt = 0F;
    private short usualtimes = 0;
    private String hiccustno;
    private String lastmslpno;
    private LocalDateTime apcyclstrt;
    private byte apcycles = 0;
    private boolean notincalnd;
    private boolean onlyincaln;
    private float sortorder = 0F;
    private String email;
    private String lspPracno;
    private String directions;
    private boolean hicmandsig;
    private String excluditms;
    private short campus = 0;
    private boolean invalidrec;
    private String lccid;
    private byte useChgtyp = 0;
    private String useGaptyp;
    private String rescat;
    private String ressubcat;
    private String mid;
    private String displayColorHex;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] displayThumbnail;
    private String textColorHex = "#000000";

    @Id
    @Column(name = "`resorce_id`", nullable = false, length = 10)
    public String getResorceId() {
        return this.resorceId;
    }

    public void setResorceId(String resorceId) {
        this.resorceId = resorceId;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }

    @Column(name = "`accountno`", nullable = false, length = 10)
    public String getAccountno() {
        return this.accountno;
    }

    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    @Column(name = "`address1`", nullable = false, length = 30)
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "`address2`", nullable = false, length = 20)
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "`can_dblbuk`", nullable = false)
    public boolean isCanDblbuk() {
        return this.canDblbuk;
    }

    public void setCanDblbuk(boolean canDblbuk) {
        this.canDblbuk = canDblbuk;
    }

    @Column(name = "`chargerate`", nullable = false, scale = 2, precision = 7)
    public float getChargerate() {
        return this.chargerate;
    }

    public void setChargerate(float chargerate) {
        this.chargerate = chargerate;
    }

    @Column(name = "`chargetype`", nullable = false, length = 5)
    public String getChargetype() {
        return this.chargetype;
    }

    public void setChargetype(String chargetype) {
        this.chargetype = chargetype;
    }

    @Column(name = "`comments`", nullable = false, length = 2147483647)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "`defaultval`", nullable = false)
    public boolean isDefaultval() {
        return this.defaultval;
    }

    public void setDefaultval(boolean defaultval) {
        this.defaultval = defaultval;
    }

    @Column(name = "`doctor_id`", nullable = false, length = 10)
    public String getDoctorId() {
        return this.doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    @Column(name = "`fax`", nullable = false, length = 14)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "`flat_charg`", nullable = false, scale = 2, precision = 7)
    public float getFlatCharg() {
        return this.flatCharg;
    }

    public void setFlatCharg(float flatCharg) {
        this.flatCharg = flatCharg;
    }

    @Column(name = "`given`", nullable = false, length = 25)
    public String getGiven() {
        return this.given;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    @Column(name = "`init_charg`", nullable = false, scale = 2, precision = 7)
    public float getInitCharg() {
        return this.initCharg;
    }

    public void setInitCharg(float initCharg) {
        this.initCharg = initCharg;
    }

    @Column(name = "`mobile`", nullable = false, length = 14)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "`paging`", nullable = false, length = 25)
    public String getPaging() {
        return this.paging;
    }

    public void setPaging(String paging) {
        this.paging = paging;
    }

    @Column(name = "`phone_ah`", nullable = false, length = 14)
    public String getPhoneAh() {
        return this.phoneAh;
    }

    public void setPhoneAh(String phoneAh) {
        this.phoneAh = phoneAh;
    }

    @Column(name = "`phone_bh`", nullable = false, length = 14)
    public String getPhoneBh() {
        return this.phoneBh;
    }

    public void setPhoneBh(String phoneBh) {
        this.phoneBh = phoneBh;
    }

    @Column(name = "`postcode`", nullable = false, length = 4)
    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @Column(name = "`company`", nullable = false, length = 30)
    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Column(name = "`providerno`", nullable = false, length = 8)
    public String getProviderno() {
        return this.providerno;
    }

    public void setProviderno(String providerno) {
        this.providerno = providerno;
    }

    @Column(name = "`qualifictn`", nullable = false, length = 40)
    public String getQualifictn() {
        return this.qualifictn;
    }

    public void setQualifictn(String qualifictn) {
        this.qualifictn = qualifictn;
    }

    @Column(name = "`rate_unit`", nullable = false, length = 15)
    public String getRateUnit() {
        return this.rateUnit;
    }

    public void setRateUnit(String rateUnit) {
        this.rateUnit = rateUnit;
    }

    @Column(name = "`resrcetype`", nullable = false, length = 10)
    public String getResrcetype() {
        return this.resrcetype;
    }

    public void setResrcetype(String resrcetype) {
        this.resrcetype = resrcetype;
    }

    @Column(name = "`schedlr_id`", nullable = false, length = 2)
    public String getSchedlrId() {
        return this.schedlrId;
    }

    public void setSchedlrId(String schedlrId) {
        this.schedlrId = schedlrId;
    }

    @Column(name = "`state`", nullable = false, length = 3)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`suburb`", nullable = false, length = 20)
    public String getSuburb() {
        return this.suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    @Column(name = "`surname`", nullable = false, length = 98)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "`title`", nullable = false, length = 5)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "`type`", nullable = false, length = 10)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "`typedetl`", nullable = false, length = 10)
    public String getTypedetl() {
        return this.typedetl;
    }

    public void setTypedetl(String typedetl) {
        this.typedetl = typedetl;
    }

    @Column(name = "`usualdurtn`", nullable = false, scale = 0, precision = 3)
    public short getUsualdurtn() {
        return this.usualdurtn;
    }

    public void setUsualdurtn(short usualdurtn) {
        this.usualdurtn = usualdurtn;
    }

    @Column(name = "`usualendt`", nullable = false, scale = 2, precision = 5)
    public float getUsualendt() {
        return this.usualendt;
    }

    public void setUsualendt(float usualendt) {
        this.usualendt = usualendt;
    }

    @Column(name = "`usualstrtt`", nullable = false, scale = 2, precision = 5)
    public float getUsualstrtt() {
        return this.usualstrtt;
    }

    public void setUsualstrtt(float usualstrtt) {
        this.usualstrtt = usualstrtt;
    }

    @Column(name = "`usualtimes`", nullable = false, scale = 0, precision = 3)
    public short getUsualtimes() {
        return this.usualtimes;
    }

    public void setUsualtimes(short usualtimes) {
        this.usualtimes = usualtimes;
    }

    @Column(name = "`hiccustno`", nullable = false, length = 10)
    public String getHiccustno() {
        return this.hiccustno;
    }

    public void setHiccustno(String hiccustno) {
        this.hiccustno = hiccustno;
    }

    @Column(name = "`lastmslpno`", nullable = false, length = 14)
    public String getLastmslpno() {
        return this.lastmslpno;
    }

    public void setLastmslpno(String lastmslpno) {
        this.lastmslpno = lastmslpno;
    }

    @Column(name = "`apcyclstrt`", nullable = false)
    public LocalDateTime getApcyclstrt() {
        return this.apcyclstrt;
    }

    public void setApcyclstrt(LocalDateTime apcyclstrt) {
        this.apcyclstrt = apcyclstrt;
    }

    @Column(name = "`apcycles`", nullable = false, scale = 0, precision = 1)
    public byte getApcycles() {
        return this.apcycles;
    }

    public void setApcycles(byte apcycles) {
        this.apcycles = apcycles;
    }

    @Column(name = "`notincalnd`", nullable = false)
    public boolean isNotincalnd() {
        return this.notincalnd;
    }

    public void setNotincalnd(boolean notincalnd) {
        this.notincalnd = notincalnd;
    }

    @Column(name = "`onlyincaln`", nullable = false)
    public boolean isOnlyincaln() {
        return this.onlyincaln;
    }

    public void setOnlyincaln(boolean onlyincaln) {
        this.onlyincaln = onlyincaln;
    }

    @Column(name = "`sortorder`", nullable = false, scale = 2, precision = 5)
    public float getSortorder() {
        return this.sortorder;
    }

    public void setSortorder(float sortorder) {
        this.sortorder = sortorder;
    }

    @Column(name = "`email`", nullable = false, length = 49)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "`lsp_pracno`", nullable = false, length = 10)
    public String getLspPracno() {
        return this.lspPracno;
    }

    public void setLspPracno(String lspPracno) {
        this.lspPracno = lspPracno;
    }

    @Column(name = "`directions`", nullable = false, length = 2147483647)
    public String getDirections() {
        return this.directions;
    }

    public void setDirections(String directions) {
        this.directions = directions;
    }

    @Column(name = "`hicmandsig`", nullable = false)
    public boolean isHicmandsig() {
        return this.hicmandsig;
    }

    public void setHicmandsig(boolean hicmandsig) {
        this.hicmandsig = hicmandsig;
    }

    @Column(name = "`excluditms`", nullable = false, length = 2147483647)
    public String getExcluditms() {
        return this.excluditms;
    }

    public void setExcluditms(String excluditms) {
        this.excluditms = excluditms;
    }

    @Column(name = "`campus`", nullable = false, scale = 0, precision = 4)
    public short getCampus() {
        return this.campus;
    }

    public void setCampus(short campus) {
        this.campus = campus;
    }

    @Column(name = "`invalidrec`", nullable = false)
    public boolean isInvalidrec() {
        return this.invalidrec;
    }

    public void setInvalidrec(boolean invalidrec) {
        this.invalidrec = invalidrec;
    }

    @Column(name = "`lccid`", nullable = false, length = 3)
    public String getLccid() {
        return this.lccid;
    }

    public void setLccid(String lccid) {
        this.lccid = lccid;
    }

    @Column(name = "`use_chgtyp`", nullable = false, scale = 0, precision = 2)
    public byte getUseChgtyp() {
        return this.useChgtyp;
    }

    public void setUseChgtyp(byte useChgtyp) {
        this.useChgtyp = useChgtyp;
    }

    @Column(name = "`use_gaptyp`", nullable = false, length = 1)
    public String getUseGaptyp() {
        return this.useGaptyp;
    }

    public void setUseGaptyp(String useGaptyp) {
        this.useGaptyp = useGaptyp;
    }

    @Column(name = "`rescat`", nullable = false, length = 10)
    public String getRescat() {
        return this.rescat;
    }

    public void setRescat(String rescat) {
        this.rescat = rescat;
    }

    @Column(name = "`ressubcat`", nullable = false, length = 10)
    public String getRessubcat() {
        return this.ressubcat;
    }

    public void setRessubcat(String ressubcat) {
        this.ressubcat = ressubcat;
    }

    @Column(name = "`mid`", nullable = false, length = 10)
    public String getMid() {
        return this.mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    @Column(name = "`DisplayColorHEX`", nullable = true, length = 20)
    public String getDisplayColorHex() {
        return this.displayColorHex;
    }

    public void setDisplayColorHex(String displayColorHex) {
        this.displayColorHex = displayColorHex;
    }

    @Column(name = "`DisplayThumbnail`", nullable = true)
    public byte[] getDisplayThumbnail() {
        return this.displayThumbnail;
    }

    public void setDisplayThumbnail(byte[] displayThumbnail) {
        this.displayThumbnail = displayThumbnail;
    }

    @Column(name = "`TextColorHEX`", nullable = true, length = 20)
    public String getTextColorHex() {
        return this.textColorHex;
    }

    public void setTextColorHex(String textColorHex) {
        this.textColorHex = textColorHex;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Resource)) return false;
        final Resource resource = (Resource) o;
        return Objects.equals(getResorceId(), resource.getResorceId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getResorceId());
    }
}