/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rosterslots generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`rosterslots`")
public class Rosterslots implements Serializable {

    private String uniqcalid;
    private int idNo;
    private LocalDateTime bdate;
    private String btime;
    private String etime;
    private String calDesc;
    private String userId;
    private byte color = 0;
    private byte icon = 0;
    private String recurstamp;
    private String blueprntcd;
    private short duration = 0;
    private String rosterId;
    private String status;
    private String usdbycalid;

    @Id
    @Column(name = "`uniqcalid`", nullable = false, length = 10)
    public String getUniqcalid() {
        return this.uniqcalid;
    }

    public void setUniqcalid(String uniqcalid) {
        this.uniqcalid = uniqcalid;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }

    @Column(name = "`b_date`", nullable = false)
    public LocalDateTime getBdate() {
        return this.bdate;
    }

    public void setBdate(LocalDateTime bdate) {
        this.bdate = bdate;
    }

    @Column(name = "`b_time`", nullable = false, length = 5)
    public String getBtime() {
        return this.btime;
    }

    public void setBtime(String btime) {
        this.btime = btime;
    }

    @Column(name = "`e_time`", nullable = false, length = 5)
    public String getEtime() {
        return this.etime;
    }

    public void setEtime(String etime) {
        this.etime = etime;
    }

    @Column(name = "`cal_desc`", nullable = false, length = 20)
    public String getCalDesc() {
        return this.calDesc;
    }

    public void setCalDesc(String calDesc) {
        this.calDesc = calDesc;
    }

    @Column(name = "`user_id`", nullable = false, length = 2)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "`color`", nullable = false, scale = 0, precision = 2)
    public byte getColor() {
        return this.color;
    }

    public void setColor(byte color) {
        this.color = color;
    }

    @Column(name = "`icon`", nullable = false, scale = 0, precision = 2)
    public byte getIcon() {
        return this.icon;
    }

    public void setIcon(byte icon) {
        this.icon = icon;
    }

    @Column(name = "`recurstamp`", nullable = false, length = 16)
    public String getRecurstamp() {
        return this.recurstamp;
    }

    public void setRecurstamp(String recurstamp) {
        this.recurstamp = recurstamp;
    }

    @Column(name = "`blueprntcd`", nullable = false, length = 5)
    public String getBlueprntcd() {
        return this.blueprntcd;
    }

    public void setBlueprntcd(String blueprntcd) {
        this.blueprntcd = blueprntcd;
    }

    @Column(name = "`duration`", nullable = false, scale = 0, precision = 3)
    public short getDuration() {
        return this.duration;
    }

    public void setDuration(short duration) {
        this.duration = duration;
    }

    @Column(name = "`roster_id`", nullable = false, length = 10)
    public String getRosterId() {
        return this.rosterId;
    }

    public void setRosterId(String rosterId) {
        this.rosterId = rosterId;
    }

    @Column(name = "`status`", nullable = false, length = 1)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`usdbycalid`", nullable = false, length = 10)
    public String getUsdbycalid() {
        return this.usdbycalid;
    }

    public void setUsdbycalid(String usdbycalid) {
        this.usdbycalid = usdbycalid;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Rosterslots)) return false;
        final Rosterslots rosterslots = (Rosterslots) o;
        return Objects.equals(getUniqcalid(), rosterslots.getUniqcalid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUniqcalid());
    }
}