/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roster generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`roster`")
public class Roster implements Serializable {

    private String rosterId;
    private int idNo;
    private LocalDateTime rostrdate;
    private String schdusrId;
    private String bluePrnt;
    private String phoneno;
    private String doctor1Id;
    private String doctor2Id;
    private String anaeth1Id;
    private String anaeth2Id;
    private String locatn1Id;
    private String locatn2Id;
    private String doc1name;
    private String ant1name;
    private String btime;
    private String etime;
    private float duration = 0F;
    private String othres1Id;
    private String othres2Id;
    private String othres3Id;
    private String othres4Id;
    private String rosternote;
    private short maxpatns = 0;
    private boolean rostnoton;
    private short slotduratn = 0;
    private String rcrtampros;
    private boolean nohdrnfotr;

    @Id
    @Column(name = "`roster_id`", nullable = false, length = 10)
    public String getRosterId() {
        return this.rosterId;
    }

    public void setRosterId(String rosterId) {
        this.rosterId = rosterId;
    }

    @Column(name = "`IdNo`", nullable = false, scale = 0, precision = 10)
    public int getIdNo() {
        return this.idNo;
    }

    public void setIdNo(int idNo) {
        this.idNo = idNo;
    }

    @Column(name = "`rostrdate`", nullable = false)
    public LocalDateTime getRostrdate() {
        return this.rostrdate;
    }

    public void setRostrdate(LocalDateTime rostrdate) {
        this.rostrdate = rostrdate;
    }

    @Column(name = "`schdusr_id`", nullable = false, length = 2)
    public String getSchdusrId() {
        return this.schdusrId;
    }

    public void setSchdusrId(String schdusrId) {
        this.schdusrId = schdusrId;
    }

    @Column(name = "`blue_prnt`", nullable = false, length = 5)
    public String getBluePrnt() {
        return this.bluePrnt;
    }

    public void setBluePrnt(String bluePrnt) {
        this.bluePrnt = bluePrnt;
    }

    @Column(name = "`phoneno`", nullable = false, length = 14)
    public String getPhoneno() {
        return this.phoneno;
    }

    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    @Column(name = "`doctor1_id`", nullable = false, length = 10)
    public String getDoctor1Id() {
        return this.doctor1Id;
    }

    public void setDoctor1Id(String doctor1Id) {
        this.doctor1Id = doctor1Id;
    }

    @Column(name = "`doctor2_id`", nullable = false, length = 10)
    public String getDoctor2Id() {
        return this.doctor2Id;
    }

    public void setDoctor2Id(String doctor2Id) {
        this.doctor2Id = doctor2Id;
    }

    @Column(name = "`anaeth1_id`", nullable = false, length = 10)
    public String getAnaeth1Id() {
        return this.anaeth1Id;
    }

    public void setAnaeth1Id(String anaeth1Id) {
        this.anaeth1Id = anaeth1Id;
    }

    @Column(name = "`anaeth2_id`", nullable = false, length = 10)
    public String getAnaeth2Id() {
        return this.anaeth2Id;
    }

    public void setAnaeth2Id(String anaeth2Id) {
        this.anaeth2Id = anaeth2Id;
    }

    @Column(name = "`locatn1_id`", nullable = false, length = 10)
    public String getLocatn1Id() {
        return this.locatn1Id;
    }

    public void setLocatn1Id(String locatn1Id) {
        this.locatn1Id = locatn1Id;
    }

    @Column(name = "`locatn2_id`", nullable = false, length = 10)
    public String getLocatn2Id() {
        return this.locatn2Id;
    }

    public void setLocatn2Id(String locatn2Id) {
        this.locatn2Id = locatn2Id;
    }

    @Column(name = "`doc1name`", nullable = false, length = 30)
    public String getDoc1name() {
        return this.doc1name;
    }

    public void setDoc1name(String doc1name) {
        this.doc1name = doc1name;
    }

    @Column(name = "`ant1name`", nullable = false, length = 30)
    public String getAnt1name() {
        return this.ant1name;
    }

    public void setAnt1name(String ant1name) {
        this.ant1name = ant1name;
    }

    @Column(name = "`b_time`", nullable = false, length = 5)
    public String getBtime() {
        return this.btime;
    }

    public void setBtime(String btime) {
        this.btime = btime;
    }

    @Column(name = "`e_time`", nullable = false, length = 5)
    public String getEtime() {
        return this.etime;
    }

    public void setEtime(String etime) {
        this.etime = etime;
    }

    @Column(name = "`duration`", nullable = false, scale = 1, precision = 5)
    public float getDuration() {
        return this.duration;
    }

    public void setDuration(float duration) {
        this.duration = duration;
    }

    @Column(name = "`othres1_id`", nullable = false, length = 10)
    public String getOthres1Id() {
        return this.othres1Id;
    }

    public void setOthres1Id(String othres1Id) {
        this.othres1Id = othres1Id;
    }

    @Column(name = "`othres2_id`", nullable = false, length = 10)
    public String getOthres2Id() {
        return this.othres2Id;
    }

    public void setOthres2Id(String othres2Id) {
        this.othres2Id = othres2Id;
    }

    @Column(name = "`othres3_id`", nullable = false, length = 10)
    public String getOthres3Id() {
        return this.othres3Id;
    }

    public void setOthres3Id(String othres3Id) {
        this.othres3Id = othres3Id;
    }

    @Column(name = "`othres4_id`", nullable = false, length = 10)
    public String getOthres4Id() {
        return this.othres4Id;
    }

    public void setOthres4Id(String othres4Id) {
        this.othres4Id = othres4Id;
    }

    @Column(name = "`rosternote`", nullable = false, length = 50)
    public String getRosternote() {
        return this.rosternote;
    }

    public void setRosternote(String rosternote) {
        this.rosternote = rosternote;
    }

    @Column(name = "`maxpatns`", nullable = false, scale = 0, precision = 4)
    public short getMaxpatns() {
        return this.maxpatns;
    }

    public void setMaxpatns(short maxpatns) {
        this.maxpatns = maxpatns;
    }

    @Column(name = "`rostnoton`", nullable = false)
    public boolean isRostnoton() {
        return this.rostnoton;
    }

    public void setRostnoton(boolean rostnoton) {
        this.rostnoton = rostnoton;
    }

    @Column(name = "`slotduratn`", nullable = false, scale = 0, precision = 4)
    public short getSlotduratn() {
        return this.slotduratn;
    }

    public void setSlotduratn(short slotduratn) {
        this.slotduratn = slotduratn;
    }

    @Column(name = "`rcrtampros`", nullable = false, length = 16)
    public String getRcrtampros() {
        return this.rcrtampros;
    }

    public void setRcrtampros(String rcrtampros) {
        this.rcrtampros = rcrtampros;
    }

    @Column(name = "`nohdrnfotr`", nullable = false)
    public boolean isNohdrnfotr() {
        return this.nohdrnfotr;
    }

    public void setNohdrnfotr(boolean nohdrnfotr) {
        this.nohdrnfotr = nohdrnfotr;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Roster)) return false;
        final Roster roster = (Roster) o;
        return Objects.equals(getRosterId(), roster.getRosterId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRosterId());
    }
}