/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryDoctorsListResponse implements Serializable {


    @ColumnAlias("cFirstLetter")
    private String cfirstLetter;

    @ColumnAlias("DrName")
    private String drName;

    @ColumnAlias("qualifictn")
    private String qualifictn;

    @ColumnAlias("Specialty1")
    private String specialty1;

    public String getCfirstLetter() {
        return this.cfirstLetter;
    }

    public void setCfirstLetter(String cfirstLetter) {
        this.cfirstLetter = cfirstLetter;
    }

    public String getDrName() {
        return this.drName;
    }

    public void setDrName(String drName) {
        this.drName = drName;
    }

    public String getQualifictn() {
        return this.qualifictn;
    }

    public void setQualifictn(String qualifictn) {
        this.qualifictn = qualifictn;
    }

    public String getSpecialty1() {
        return this.specialty1;
    }

    public void setSpecialty1(String specialty1) {
        this.specialty1 = specialty1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryDoctorsListResponse)) return false;
        final QryDoctorsListResponse qryDoctorsListResponse = (QryDoctorsListResponse) o;
        return Objects.equals(getCfirstLetter(), qryDoctorsListResponse.getCfirstLetter()) &&
                Objects.equals(getDrName(), qryDoctorsListResponse.getDrName()) &&
                Objects.equals(getQualifictn(), qryDoctorsListResponse.getQualifictn()) &&
                Objects.equals(getSpecialty1(), qryDoctorsListResponse.getSpecialty1());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCfirstLetter(),
                getDrName(),
                getQualifictn(),
                getSpecialty1());
    }
}