/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.mobiwiz.healthyops.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class HealthyOpsProcedureExecutorServiceImpl implements HealthyOpsProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(HealthyOpsProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("HealthyOpsWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}